### PR TITLE
tmux segfaults against latest ncurses

### LINKED ISSUE #3531: 3.3a, latest-git: segfaults against latest ncurses-6.4-20230408 or higher
### Issue description

running tmux (any TERM) against the latest snapshots of ncurses, then clicking the mouse a few times in the terminal, makes it (server) segfault.

### Required information

```
(lldb) bt
* thread #1, name = 'tmux: server', stop reason = signal SIGSEGV
  * frame #0: 0x00005590b3c8f833 tmux`tty_puts(tty=0x00007f257eb82548, s=0x0000000000000000) at tty.c:570:5
    frame #1: 0x00005590b3c94c4c tmux`tty_set_selection [inlined] tty_putcode_ptr2(code=TTYC_MS, a=0x000000000007af56, b=0x00007f257f78be90, tty=0x00007f257eb82548) at tty.c:543:5
    frame #2: 0x00005590b3c94c3c tmux`tty_set_selection at tty.c:2104:2
    frame #3: 0x00005590b3c94bfb tmux`tty_set_selection(tty=0x00007f257eb82548, buf="\n\n ", len=1) at tty.c:2089:1
    frame #4: 0x00005590b3c94bbe tmux`tty_write(cmdfn=(tmux`tty_cmd_setselection at tty.c:2085:2), ctx=0x00007fff9a39f5f8) at tty.c:1630:3
    frame #5: 0x00005590b3c7e776 tmux`screen_write_setselection(ctx=0x00007fff9a39f6d0, str="\n\n ", len=1) at screen-write.c:2096:2
    frame #6: 0x00005590b3caab93 tmux`window_copy_copy_buffer.isra.0(prefix=0x0000000000000000, buf=0x00007f257f78e8b0, len=1, wme=<unavailable>) at window-copy.c:4573:3
    frame #7: 0x00005590b3c98e4a tmux`window_copy_cmd_copy_pipe_no_clear(cs=<unavailable>) at window-copy.c:2027:2
    frame #8: 0x00005590b3c99f8b tmux`window_copy_cmd_copy_pipe_and_cancel(cs=<unavailable>) at window-copy.c:2049:2
    frame #9: 0x00005590b3c99b4a tmux`window_copy_command(wme=0x00007f257f583c70, c=<unavailable>, s=0x00007f257f000610, wl=0x00007f257f481c90, args=<unavailable>, m=<unavailable>) at window-copy.c:2916:13
    frame #10: 0x00005590b3c5cabd tmux`cmd_send_keys_exec(self=0x00007f257f598a30, item=0x00007f257f611b10) at cmd-send-keys.c:176:3
    frame #11: 0x00005590b3c57265 tmux`cmdq_next at cmd-queue.c:647:11
    frame #12: 0x00005590b3c5702a tmux`cmdq_next(c=<unavailable>) at cmd-queue.c:763:14
    frame #13: 0x00005590b3c84822 tmux`server_loop at server.c:270:14
    frame #14: 0x00005590b3c4505d tmux`main [inlined] proc_loop(loopcb=<unavailable>, tp=0x00007f257f080510) at proc.c:222:42
    frame #15: 0x00005590b3c45058 tmux`main at server.c:251:2
    frame #16: 0x00005590b3c44b26 tmux`main at client.c:164:8
    frame #17: 0x00005590b3c4488d tmux`main at client.c:287:7
    frame #18: 0x00005590b3c44731 tmux`main(argc=<unavailable>, argv=<unavailable>) at tmux.c:519:2
    frame #19: 0x00007f258fe92aad ld-musl-x86_64.so.1`libc_start_main_stage2(main=(tmux`main at tmux.c:333:1), argc=1, argv=0x00007fff9a39fd58) at __libc_start_main.c:95:2
    frame #20: 0x00005590b3c45ab4 tmux`_start + 22
```

seemingly, the tty_term_ptr2 outputs a null pointer (somewhere in there tparm is called, i assume, incorrectly).

ncurses """commits""" of relevance:  

https://github.com/ThomasDickey/ncurses-snapshots/commit/a6d3f92bb5bba1a71c7c3df39497abbe5fe999ff  
https://github.com/ThomasDickey/ncurses-snapshots/commit/d5f041afdf80a81ed00d50fc4fa31f278c222e7b  

similar bug reports in other applications broken by the same thing for context:

https://bugs.gentoo.org/904277  
https://bugs.gentoo.org/904263  

the vim one is strange, as it looks like the same issue (null tparm output)

Please provide the following information:

* tmux version (`tmux -V`). `tmux 3.3a`
* Platform (`uname -sp`). `Linux unknown`
* $TERM inside and outside of tmux (`echo $TERM`). `xterm`
* Logs from tmux (`tmux kill-server; tmux -vv new`). dunno how to get this with it segfaulting in the server

### PR DESCRIPTION
**Pull request by citrus-it**
This fixes https://github.com/tmux/tmux/issues/3531
that showed up after #27 updated ncurses to a newer version.

### CODE REVIEW

File: build/tmux/build.sh [hunk 1]
```diff
@@ -18,7 +18,7 @@
 . ../../lib/build.sh
 
 PROG=tmux
-VER=3.3
+VER=3.3a
```
Comment (jclulow) [inline build/tmux/build.sh:21]: Will this result in a version bump for the IPS package?  If not, we should do a micro roll of the branch version

Comment (citrus-it) [reply build/tmux/build.sh:21]: Yes, it becomes 3.3.1

**Review by jclulow — APPROVED** [review]
